# Generated by Django 4.1.13 on 2024-10-01 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactenquiry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conceptenquiry',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='conceptenquiry',
            name='websiteLink',
        ),
    ]
