# Generated by Django 4.1.13 on 2024-10-01 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactenquiry', '0002_remove_conceptenquiry_phone_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='conceptEnquiry',
            new_name='contactEnquiry',
        ),
    ]
